### ISSUE TITLE
CRAN-release

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/ptable#12]
hi @tenderle  in order to help people install the [**cellKey**](https://github.com/sdcTools/cellKey) package, it should be available through CRAN. Thus, also the **pTable** package needs to be on CRAN. Can you prepare a release? In case you need any help, I  can of course help you!

**Comment by tenderle** [comment]
[Version 1.0.0 released on CRAN](https://cran.r-project.org/package=ptable)
