### ISSUE TITLE
tag for prototype

### ISSUE THREAD

**Issue by bernhard-da** [sdcTools/ptable#13]
hi @tenderle 

could you please provide a git-tag to the version of the package that you deem stable enough for the prototype testing? something like

```
git tag -a "ptable_prototype" -m "version for prototype testing"
git push --tags
```

so that i can reference to this specific version when providing instructions for the prototype testing, eg

```
devtools::install_github("sdcTools/ptable", ref="ptable_prototype", build_vignette=TRUE, dependencies=TRUE)
````

i've already done this for cellKey.

**Comment by tenderle** [comment]
Hi @bernhard-da,

ok, I will provide a release (zip and tar.gz) with a tag. This can be done using the frontend of github.

However, do you mean to add the tag to the latest commit (sdcTools/ptable/...) too? Then I will have to use your example within my terminal and then commit. Is this what you mean? Will this tag stick to the newer versions (commits) I produce too? Or do I have to remove the tag afterwards or update it always?

**Comment by bernhard-da** [comment]
hi @tenderle 

yes. this is the same (drafting a release and creating the tag while doing so) as the terminal-way i posted in the issue.

a tag is nothing special, it is just a reference to a specific commit which will "stick". if you create a tag (eg. "v1.0") and then later add commits and draft a new release (eg. create tag "v1.1") the v1.0 tag just references the old version.  this is quite handy because you can easily install any (tagged) version directly with `devtools::install_github`  by just changing the `ref` argument.

**Comment by tenderle** [comment]
thx @bernhard-da,, 

let's say I use the terminal solution, and if I don't update the tag in my terminal when I commit some new code, will the new commit have still the old tag? Then you will refer to the new code?

**Comment by bernhard-da** [comment]
@tenderle  if you tag now!, the tag created will refer to commit https://github.com/sdcTools/ptable/commit/9a4eb4ac95a6294e3ea1cc7b43d750d00e766721 and will always to so. if you add additional commits and add another tag later, this one will refer to the commit that is the latest at the time of tagging. 

the old tag will be kept and will always refer to the same commit id

**Comment by tenderle** [comment]
Ok, thx @bernhard-da now I got it.

**Comment by tenderle** [comment]
@bernhard-da, after resolving some conflicting commit and pull request issues, I updated the fork on sdcTools and released the newest [version](https://github.com/sdcTools/ptable/releases/tag/v0.1.13_prototype) with the tag `v0.1.13_prototype`.

**Comment by tenderle** [comment]
@bernhard-da, thanks so far. 

 I don't use vignettes so far, but you state it in your readme of the new repo:

`install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE)`

I don't know if this is an issue.

Than a further question: do you know why the downloaded file `ptable-0.1.13_prototype.tar.gz` is using my whole tag but not the first letter "v"?

**Comment by bernhard-da** [comment]
@tenderle if there is no vignette, it won't be used. so no problem there

as for your second question: which downloaded file are you referring to?

**Comment by tenderle** [comment]
I copied your readme of the new repo and adapted it to the ptable package: [***subfolder***](https://github.com/sdcTools/protoTestCensus/tree/master/CellKey/ptable).

Following your example I provide the link:
https://github.com/sdcTools/ptable/archive/v0.1.13_prototype.tar.gz

Whereas the link uses the tag, the downloaded file reads different:
`ptable-0.1.13_prototype.tar.gz`

The same goes for your package.

**Comment by bernhard-da** [comment]
very strange, i have no idea. funny thing is, when i use any cli download tool, the file-name is not changed

```
wget https://github.com/sdcTools/ptable/archive/v0.1.13_prototype.tar.gz
```

results in `v0.1.13_prototype.tar.gz` while downloading in the browser results in the behaviour you described. i have no idea why this happens but it is not really a problem i think...

**Comment by tenderle** [comment]
I neither had a glue, but thx

**Comment by tenderle** [comment]
@bernhard-da I have updated the prototype [version](https://github.com/sdcTools/ptable/releases/tag/v0.2.0_prototype), the new tag is `v0.2.0_prototype`. Can you update your instructions? (The changes I did shouldn't affect your package).

**Comment by bernhard-da** [comment]
@tenderle updated reference in https://github.com/sdcTools/protoTestCensus/commit/a751708157092ae062a96bcfead58428766ec4d1
