### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/ptable#15]
Trying to install from github with
`install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE)`, I get some errors. Installation from within RStudio.

First I get
`These packages have more recent versions available. Which would you like to update?`
and a list of package names. I then select `All` to update all of those packages.

Then I get some errors, e.g.,
`Error: (converted from warning) cannot remove prior installation of package ‘digest’`

Restarting RStudio I get with `library(devtools)` the message
`Error: package or namespace load failed for ‘devtools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘digest’
In addition: Warning message:
package ‘devtools’ was built under R version 3.4.4`

Then I have to re-install the digest-package and then can use `library(devtools)` again.

Then run
`install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE)`,  
again. Get a list of packages to update, select `All` and then digest-packge gets installed, but now error
`Error: (converted from warning) cannot remove prior installation of package ‘glue’`.

Then I have to iterate untill no error...

Note: the first package I got this "cannot remove prior installation" error with, was backports-package.

**Comment by bernhard-da** [comment]
@ppdewolf i guess you just have multiple places where R packages can be installed to.

i guess that when looking at the output of

```
.libPaths()
```

you do not have write-permissions to the first (default) directory listed here. this typically occurs when R was installed by a (windows)-admin.

provide explicitely the library-location where the packages should be installed to, eg.

```
install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE, lib="/path/to/my/writetable/folder")
```

where `"/path/to/my/writetable/folder"` is a folder your user can write to should work. alternatively, upgrade/install using admin-rights (i don't know how this works in windows)

**Comment by tenderle** [comment]
I got some similar errors (not able to remove digest). After removing the packages, I was not able to reproduce the error. @bernhard-da, does something like this - prior to the `github_install()` call - help?

```
if (is.element("ptable", installed.packages()[,1])) remove.packages("ptable")
install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE)
```

**Comment by ppdewolf** [comment]
I have full administrative rights at this machine. 
And I checked: I manually can cretae directories in both directories of output of `.libPaths()` without having to provide a password.

**Comment by bernhard-da** [comment]
@tenderle i don't think that this would help. could it be that some package was already loaded?

@ppdewolf it might also be that (some) pkgs were already loaded. try the following steps. but before you start, restart your session (in rstudio: session --> restart R)

```
## update all packages
update.packages(ask=FALSE)

## reinstall ptable
install_github("sdcTools/ptable", ref="v0.1.13_prototype", build_vignette=TRUE, dependencies=TRUE)
```

**Comment by ppdewolf** [comment]
I did get it installed eventually (using the "sequential"  approach described in my first message). And can't reproduce the error anymore (unless if I de-install things first).
Just wanted to let you know and perhaps have some information about this in the installation instructions?
Somehow, it seems that devtools was using digest, while the installation tried to update digest from within a function from devtools?

**Comment by bernhard-da** [comment]
@ppdewolf yes, probably may be due to the devtools package being out of date also. i've updated the installation instructions fin https://github.com/sdcTools/cellKey/commit/ecd2abce773307ed15eff99d549f17fa7d8c6018 and https://github.com/sdcTools/protoTestCensus/commit/fc9dffc7ce1a8204dd629a1ec7020b93f9b60d56

**Comment by ppdewolf** [comment]
@bernhard-da @tenderle 
In the desciptions on prototestCensus you write:
`install.packages(ask=FALSE)` is good idea to start with.
I think you mean `update.packages(ask=FALSE)`?

**Comment by bernhard-da** [comment]
@ppdewolf thx for spotting, already updated.

**Comment by tenderle** [comment]
Thx @bernhard-da, then let me summarize your solution:
```
# update all packages
update.packages(ask=FALSE)

# install devtools
if (!require("devtools")) install.packages("devtools")
library(devtools)

# and install the package directly from github
install_github("sdcTools/ptable", ref="v0.2.0_prototype", build_opts="--build-vignettes", dependencies=c("Imports","Depends"))
```
