### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/ptable#17]
I installed the 0.2.0_prototype version.
If I then use the command
`pt_vignette()`
I get an error:
`Error in RShowDoc("introduction", package = "ptable") : 
  no documentation for ‘introduction’ found in package ‘ptable’`

**Comment by tenderle** [comment]
@ppdewolf, have you used the argument `build_vignette=TRUE`?

**Comment by ppdewolf** [comment]
This is what I did:

```
install_github("sdcTools/ptable",` ref="v0.2.0_prototype", build_vignette=TRUE, dependencies=TRUE)
Downloading GitHub repo sdcTools/ptable@v0.2.0_prototype
These packages have more recent versions available.
Which would you like to update?`

1:   cellKey (f879032c2... -> ecd2abce7...) [GitHub]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 
√  checking for file 'C:\Users\pwof\AppData\Local\Temp\RtmpI1201H\remotes26a05af627b2\sdcTools-ptable-766efe1/DESCRIPTION' (563ms)
-  preparing 'ptable':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ptable_0.2.0.tar.gz'
   
Installing package into ‘C:/Users/pwof/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'ptable' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (ptable)
library(ptable)
pt_vignette()
Error in RShowDoc("introduction", package = "ptable") : 
  no documentation for ‘introduction’ found in package ‘ptable’
```

**Comment by ppdewolf** [comment]
Nope. 😢 

In the description in protoTestCensus it is mentioned `intall.packages(ask=FALSE)`. That doesn't work.  Changed it to `update.packages(ask=FALSE)`. That worked (did updates) but no solution for showing the vignette...

After `unpdate.packages(ask=FALSE)` is did 
`install_github("sdcTools/ptable", ref="v0.2.0_prototype", build_vignette=TRUE, dependencies=TRUE, force=TRUE)` to re-install the 0.2.0_prototype version. Still no vignette shown.

@bernhard-da Do you have any idea?

**Comment by ppdewolf** [comment]
When I manually try to knit the vignette, I get the following error message. Perhaps this helps?
```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS vignettePTABLE.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output vignettePTABLE.tex --template "C:\Users\pwof\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" --filter pandoc-citeproc 
pandoc-citeproc.exe: Could not find bibtex.bib
pandoc.exe: Error running filter pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS vignettePTABLE.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output vignettePTABLE.tex --template "C:\Users\pwof\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" --filter pandoc-citeproc' had status 83 
Execution halted
```

**Comment by tenderle** [comment]
@ppdewolf, does the Vignette of `cellKey` (i.e. `ck_vignette()`) work?

**Comment by ppdewolf** [comment]
When I manually try to knit the vignette, I get an HTML file where the references (Marley and Sarah) do not show up correctly: the links open a mail-window and at the end of the document the References section is empty.

If I manually try to knit the vignette to pdf, I get after setting working directory to the place where the `vignettePTABLE.rmd` and `bibtex.bib` are located:

```output file: vignettePTABLE.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS vignettePTABLE.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output vignettePTABLE.tex --template "C:\Users\pwof\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" --filter pandoc-citeproc 

Output created: vignettePTABLE.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'vignettePTABLE.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "vignettePTABLE.tex"' had status 1 
2: In readLines(logfile) :
  incomplete final line found on 'vignettePTABLE.log'
Execution halted```

**Comment by ppdewolf** [comment]
If I do `??cellkey` in Rstudio, I do get the help pages with a vignette cellkey::introduction.
(cellkey version 0.13.0)

**Comment by tenderle** [comment]
@bernhard-da, do we need the s in vignette***s***, i.e. `build_vignettes = TRUE` (I can't use the `install_github` function in my office to verify this issue)

**Comment by tenderle** [comment]
@ppdewolf, maybe it is the build_vignette**s** issue? Could you try installing the package again trying `install_github("sdcTools/ptable", ref="v0.2.0_prototype", build_vignettes=TRUE, dependencies=TRUE, force=TRUE)`?

Or it is the bibtex issue (the only difference to the cellkey Vignette).

**Comment by ppdewolf** [comment]
No, doesn't help.

**Comment by tenderle** [comment]
OK, last try.  Since I don't have the possibility to apply `install_github()` at the office, I always use a modified version of the code @bernhard-da gave to me. Using the following code I am able to build and open the Vignette afterwards:
```
install_pt_local <- function(branch="master", repository="sdcTools") {
  stopifnot(branch %in% c("master"))
  stopifnot(repository %in% c("tenderle","sdcTools"))
  
  if (!requireNamespace("stringi", quietly = TRUE)) install.packages("stringi")
  if (!requireNamespace("stringr", quietly = TRUE)) install.packages("stringr")
  
  f <- tempfile(fileext = ".zip")
  u <- file.path(paste0("https://github.com/",repository,"/ptable/archive"), paste0(branch,".zip"))
  download.file(u, destfile = f)

  td <- tempdir()
  unzip(f, exdir=td, list=FALSE)
  file.remove(f)

  devtools::install(file.path(td,paste0("ptable-",branch)), build_vignettes = TRUE, dependencies = c("Depends","Imports"))
}
install_pt_local(branch="master", repository = "sdcTools")

library(ptable)
pt_vignette()
```
If this does not work, I have to check it tomorrow when I work at home.

**Comment by bernhard-da** [comment]
@tenderle @ppdewolf 

sorry for the late reply. i think the problem is, that devtools has split into "subpackages" and slightly changed the parameters. for it is now actually the `remotes` package that deals with installation from github.

anyway, the following should work. if it does, we should change all the documentation:

```
install_github("sdcTools/ptable", ref="v0.2.0_prototype", dependencies=c("Depends","Imports"), force=TRUE, build_opts="--no-manual --build-vignettes")
install_github("sdcTools/cellKey", ref="v0.15_0", dependencies=TRUE, force=TRUE, build_opts="--no-manual --build-vignettes")
```
note also the differences in argument `dependencies` between the two packages.

@ppdewolf could you please quickly test?

**Comment by ppdewolf** [comment]
The first line works: the ptable vignette is build (although the references still do not work correctly).

The second line gives:
```
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/sdcTools/cellKey/commits/v0.15_0'
```

**Comment by bernhard-da** [comment]
@ppdewolf ok, we're getting there.

the second error was a typo, the correct name of the tag is "v0.15.0"  (i've also corrected it in my previous answer)

also: i included the `--no-manual` because i tested in a windows virtual machine and got some message because latex was not installed, but perhaps this is not a problem at all and one can use:

```
install_github("sdcTools/ptable", ref="v0.2.0_prototype", dependencies=c("Depends","Imports"), force=TRUE, build_opts="--build-vignettes")
install_github("sdcTools/cellKey", ref="v0.15_0", dependencies=TRUE, force=TRUE, build_opts="--build-vignettes")
```
as for the references. perhaps inline bibtex (formated as yaml) as shown in https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html works @tenderle ?

**Comment by ppdewolf** [comment]
Figured the typo out as well 😄

**Comment by tenderle** [comment]
@bernhard-da, for me the vignettes are working on different Windows PCs (either with `install_github()` or the code I posted above) but I can give it a try.

**Comment by bernhard-da** [comment]
@ppdewolf i've updated the instructions already.

**Comment by bernhard-da** [comment]
@tenderle in https://github.com/sdcTools/protoTestCensus/commit/11efb6250e76ed362fcbe9bb279a5daddc45418f i've also updated the instructions for ptable alone

**Comment by tenderle** [comment]
thx @bernhard-da

**Comment by ppdewolf** [comment]
@bernhard-da Thanks! 👍 
@tenderle It does not produce errors. In the resulting vignette (html-file) the references look like:
![capture1](https://user-images.githubusercontent.com/19729987/49376790-bdbed780-f708-11e8-9be5-723795c02251.PNG)
(the links are something like `mailto:*@marley2011`)
and in the References section there are no items:
![capture2](https://user-images.githubusercontent.com/19729987/49376789-bdbed780-f708-11e8-94e5-4db24eddd6fb.PNG)

**Comment by tenderle** [comment]
With [CRAN release1.0.0](https://cran.r-project.org/package=ptable), the vignette was built correctly.
