### ISSUE TITLE
Small bug when saving ptable via Shiny interface

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/ptable#20]
**Using version 0.2.0**

When saving a ptable for TauArgus via shiny interface, there is no first line for 0 cells.
When saving the same ptable via an R script (e.g. via RStudio), there is a first line for 0 cells.

So depending on the way you save the ptable, you get different output.

**Comment by tenderle** [comment]
thx for spotting this issue, @ppdewolf 

I will add the row with the next release.

**Comment by tenderle** [comment]
Replaced download buttons by code snippet that can be used (copy&paste)
